language: python
python:
  - "3.8"
install:
  - pip install -r requirements.txt
script:
  - ./code_style.sh && ./run_tests.sh
after_success:
  - coveralls
  - semantic-release publish

deploy:
  provider: script
  script: bash docker_push.sh
  on:
    tags: true
