name: Build And Test

on:
  push:
    branches:
      - '*'
    tags:
      - '*'

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.8", "3.9", "3.10", "3.11"]

    steps:
      - uses: actions/checkout@v3
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: Code Style
        run: |
          ./code_style.sh
      - name: Test
        run: |
          ./run_tests.sh

  release:
    runs-on: ubuntu-latest
    concurrency: release
    environment: Production
    if: github.repository == 'andrewjw/glowprom' && github.ref == 'refs/heads/master'
    needs: build
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Set up Python 3.11
        uses: actions/setup-python@v4
        with:
          python-version: 3.11
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: Submit Coverage
        run: |
          ./run_tests.sh
          COVERALLS_REPO_TOKEN=${{ secrets.GLOWPROM_COVERALLS_REPO_TOKEN }} coveralls
      - name: Release
        run: |
          git config --global user.email "andrewjwilkinson@gmail.com"
          git config --global user.name "Andrew Wilkinson"
          export VERSION=$(semantic-release print-version)
          if [ ! -z "$VERSION" ]; then
             GH_TOKEN=${{ secrets.GITHUB_TOKEN }} PYPI_TOKEN=${{ secrets.PYPI_TOKEN }} semantic-release publish
             DOCKER_TOKEN=${{ secrets.DOCKER_TOKEN }} TAG=$VERSION ./docker_push.sh
          fi
 
